/**
 * extract_acukg_full.js
 * Reads all AcuKG JSON files + Chinese names and produces a comprehensive acukg.js 
 * that includes: zhName, pinyin, en, indications, location (part_of), nearby anatomy (located_near)
 * Also does Chinese translation lookup for anatomy terms.
 */

const fs = require('fs');
const path = require('path');

const BASE = path.join(__dirname, 'AcuKG-Knowledge-graph-for-medical-acupuncture', 'AcuKG_json');

function readNDJSON(file) {
    const content = fs.readFileSync(path.join(BASE, file), 'utf-8');
    return content.trim().split('\n').map(l => {
        try { return JSON.parse(l.trim()); } catch { return null; }
    }).filter(Boolean);
}

// Load all source files
const zhNames    = readNDJSON('Chinesename.json');
const enNames    = readNDJSON('Englishname.json');
const pinyin     = readNDJSON('pinyinname.json');
const indic      = readNDJSON('Indication.json');
const partOf     = readNDJSON('part_of.json');
const locNear    = readNDJSON('located_near.json');
const nearAcu    = readNDJSON('near_acupoint.json');

// --- Build index maps ---
const zhMap    = {};
const enMap    = {};
const pyMap    = {};
const indMap   = {};   // code -> [indication strings]
const locMap   = {};   // code -> [anatomy strings]
const nearMap  = {};   // code -> [anatomy strings]
const nearAcuMap = {}; // code -> [acupoint codes]

zhNames.forEach(r  => { if (r.Acupoint_Code) zhMap[r.Acupoint_Code]  = r.Chinese_Name; });
enNames.forEach(r  => { if (r.Acupoint_Code) enMap[r.Acupoint_Code]  = r.English_Name; });
pinyin.forEach(r   => { if (r.Acupoint_Code) pyMap[r.Acupoint_Code]  = r.Pinyin_Name; });

indic.forEach(r => {
    const c = r.Acupoint_Code;
    if (!c) return;
    if (!indMap[c]) indMap[c] = [];
    if (r.Indication) indMap[c].push(r.Indication);
});

partOf.forEach(r => {
    const c = r.Acupoint_Code;
    if (!c || !r.Anatomy) return;
    if (!locMap[c]) locMap[c] = [];
    // Only take the most specific: Relation + Anatomy
    const desc = `${r.Relation} ${r.Anatomy}`;
    if (!locMap[c].includes(desc)) locMap[c].push(desc);
});

locNear.forEach(r => {
    const c = r.Acupoint_Code ? r.Acupoint_Code.trim() : null;
    if (!c || !r.Anatomy) return;
    if (!nearMap[c]) nearMap[c] = [];
    if (!nearMap[c].includes(r.Anatomy)) nearMap[c].push(r.Anatomy);
});

nearAcu.forEach(r => {
    const c = r.Acupoint_Code ? r.Acupoint_Code.trim() : null;
    if (!c || !r.Acupoint) return;
    if (!nearAcuMap[c]) nearAcuMap[c] = [];
    nearAcuMap[c].push(r.Acupoint.trim().toUpperCase());
});

// Collect all unique codes
const allCodes = new Set([
    ...Object.keys(zhMap),
    ...Object.keys(enMap),
    ...Object.keys(pyMap),
]);

const meridianNames = {
    LU: '手太阴肺经', LI: '手阳明大肠经', ST: '足阳明胃经', SP: '足太阴脾经',
    HT: '手少阴心经', SI: '手太阳小肠经', BL: '足太阳膀胱经', KI: '足少阴肾经',
    PC: '手厥阴心包经', TE: '手少阳三焦经', GB: '足少阳胆经', LR: '足厥阴肝经',
    GV: '督脉', CV: '任脉',
};

const result = [];
allCodes.forEach(code => {
    const norm = code.trim().toUpperCase();
    const prefix = norm.replace(/[0-9]/g, '');
    const num = parseInt(norm.replace(/[^0-9]/g, ''));
    
    const entry = {
        code: norm,
        zh: zhMap[code] || '',
        pinyin: pyMap[code] || '',
        en: enMap[code] || '',
        meridian: meridianNames[prefix] || '经外奇穴',
        meridianCode: prefix,
        number: num || 0,
        indications: [...new Set(indMap[code] || [])],
        location: locMap[code] ? locMap[code].slice(0, 4) : [],  // Keep top 4 entries
        nearAnatomy: nearMap[code] ? [...new Set(nearMap[code])].slice(0, 6) : [],
        nearAcupoints: nearAcuMap[code] ? [...new Set(nearAcuMap[code])] : [],
    };
    
    result.push(entry);
});

// Sort: by meridian prefix alphabetically, then by number
result.sort((a, b) => {
    if (a.meridianCode < b.meridianCode) return -1;
    if (a.meridianCode > b.meridianCode) return 1;
    return a.number - b.number;
});

const output = `// Auto-generated by extract_acukg_full.js — DO NOT EDIT MANUALLY
// Contains ${result.length} acupoints with full location and indication data
const acuKGData = ${JSON.stringify(result, null, 0)};
if (typeof window !== 'undefined') window.acuKGData = acuKGData;
if (typeof module !== 'undefined') module.exports = acuKGData;
`;

fs.writeFileSync(path.join(__dirname, 'acukg.js'), output, 'utf-8');
console.log(`✅ Successfully written acukg.js with ${result.length} acupoints.`);

// Print a preview
console.log('Sample entry:', JSON.stringify(result.find(r => r.code === 'ST36'), null, 2));
